import { StyleSheet, Platform } from 'react-native';
import Colors from '../constants/colors';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  actionRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 24,
  },
  actionButtonOutline: {
    flex: 1,
    height: 44,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  actionButtonOutlineText: {
    color: '#334155',
    fontSize: 13,
    fontWeight: '600',
  },
  actionButtonSolid: {
    flex: 1,
    height: 44,
    backgroundColor: Colors.brandGreen,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  actionButtonSolidText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '600',
  },
  statEmojiIcon: {
    fontSize: 18,
  },
  walletCard: {
    backgroundColor: Colors.brandNavy,
    borderRadius: 16,
    padding: 18,
    marginBottom: 24,
  },
  walletHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#1E293B',
    paddingBottom: 16,
    marginBottom: 12,
  },
  walletTitle: {
    color: Colors.secondary,
    fontSize: 12,
    marginBottom: 4,
  },
  walletBalance: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: 'bold',
  },
  walletDepositBtn: {
    backgroundColor: Colors.brandGreen,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
  },
  walletDepositText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: 'bold',
  },
  walletFooter: {
    flexDirection: 'row',
    gap: 16,
  },
  walletFooterItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  statusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  walletFooterText: {
    color: Colors.secondary,
    fontSize: 12,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: Colors.brandNavy,
    marginBottom: 12,
  },
  demographicCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 16,
    padding: 18,
    marginBottom: 24,
  },
  totalRow: {
    alignItems: 'center',
    marginBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    paddingBottom: 12,
  },
  totalVal: {
    fontSize: 28,
    fontWeight: 'bold',
    color: Colors.brandNavy,
  },
  totalLabel: {
    fontSize: 12,
    color: Colors.secondary,
    fontWeight: '600',
    marginTop: 2,
  },
  barChartContainer: {
    gap: 12,
  },
  demographicRow: {
    width: '100%',
  },
  demographicLabelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  demographicNameContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  colorIndicator: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  demographicName: {
    fontSize: 12,
    color: '#475569',
  },
  demographicPct: {
    fontSize: 12,
    fontWeight: 'bold',
    color: Colors.brandNavy,
  },
  barBackground: {
    height: 6,
    backgroundColor: '#F1F5F9',
    borderRadius: 3,
    overflow: 'hidden',
  },
  barForeground: {
    height: '100%',
    borderRadius: 3,
  },
  recentSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  viewAllText: {
    fontSize: 13,
    color: Colors.brandGreen,
    fontWeight: '500',
  },
  activityCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 16,
    marginBottom: 24,
  },
  activityRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  lastActivityRow: {
    borderBottomWidth: 0,
  },
  activityLeft: {
    flex: 1,
  },
  patientId: {
    fontSize: 13,
    fontWeight: 'bold',
    color: Colors.brandNavy,
    marginBottom: 2,
  },
  activitySub: {
    fontSize: 12,
    color: '#64748B',
  },
  activityRight: {
    alignItems: 'flex-end',
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    marginBottom: 4,
  },
  statusSuccess: {
    backgroundColor: Colors.brandGreenSoft,
  },
  statusPending: {
    backgroundColor: '#FEF3C7',
  },
  statusSuccessText: {
    fontSize: 12,
    fontWeight: '600',
    color: Colors.brandGreenPressed,
  },
  statusPendingText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#B45309',
  },
  activityTime: {
    fontSize: 12,
    color: Colors.secondary,
  },
  pricingCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 16,
    padding: 18,
    marginBottom: 24,
  },
  pricingDesc: {
    fontSize: 12,
    color: '#64748B',
    lineHeight: 16,
    marginBottom: 16,
  },
  pricingInputGroup: {
    marginBottom: 12,
  },
  pricingInputLabel: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#475569',
    marginBottom: 4,
  },
  pricingInput: {
    height: 38,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 8,
    paddingHorizontal: 12,
    fontSize: 13,
    color: Colors.brandNavy,
    backgroundColor: '#F8FAFC',
  },
  pricingSubmitBtn: {
    backgroundColor: Colors.brandGreen,
    borderRadius: 8,
    height: 38,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 8,
  },
  pricingSubmitBtnText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: 'bold',
  },
  quickActionsGrid: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 24,
  },
  quickActionCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 14,
    padding: 12,
    alignItems: 'center',
    justifyContent: 'center',
    ...Platform.select({
      web: {
        transition: 'all 0.2s ease',
        cursor: 'pointer',
      }
    }),
  },
  quickActionIconContainer: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: Colors.brandGreenSoft,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  quickActionIcon: {
    fontSize: 16,
  },
  quickActionLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#334155',
    textAlign: 'center',
  },
  doctorsCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 16,
    padding: 16,
    marginBottom: 24,
  },
  doctorItemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  doctorItemLeft: {
    flex: 1,
  },
  doctorItemName: {
    fontSize: 13,
    fontWeight: 'bold',
    color: Colors.brandNavy,
  },
  doctorItemEmail: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 2,
  },
  roleBadgeStyle: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  roleBadgeText: {
    fontSize: 12,
    fontWeight: '600',
  },
  emptyChartContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 24,
  },
  emptyChartCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 3,
    borderColor: '#E2E8F0',
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  emptyChartPercent: {
    fontSize: 14,
    fontWeight: 'bold',
    color: Colors.secondary,
  },
  emptyChartText: {
    fontSize: 12,
    color: Colors.secondary,
  },
  tableHeaderRow: {
    flexDirection: 'row',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 16,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
  },
  tableHeaderCell: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#64748B',
    textTransform: 'uppercase',
  },
  patientNameText: {
    fontSize: 12,
    color: '#334155',
    fontWeight: '500',
    marginTop: 2,
  },
  activityTableCellText: {
    fontSize: 12,
    color: '#475569',
    alignSelf: 'center',
  },
  page: { paddingTop: 24, paddingBottom: 40 },
  kpiStrip: { flexDirection: 'row', marginTop: 20, backgroundColor: Colors.surface, borderWidth: 1, borderColor: Colors.border, borderRadius: 14, overflow: 'hidden' },
  kpiStripWrap: { flexWrap: 'wrap' },
  kpi: { minWidth: 0, paddingVertical: 16, paddingHorizontal: 20 },
  kpiFill: { flex: 1 },
  kpiHalf: { width: '50%' },
  kpiMain: { backgroundColor: Colors.brandGreenSoft },
  kpiBorderLeft: { borderLeftWidth: 1, borderLeftColor: Colors.border },
  kpiBorderTop: { borderTopWidth: 1, borderTopColor: Colors.border },
  kpiLabel: { fontSize: 13, fontWeight: '600', color: Colors.slateMuted },
  kpiValue: { fontSize: 22, fontWeight: '700', color: Colors.brandNavy, marginTop: 6, fontVariant: ['tabular-nums'] },
  kpiValueMain: { fontSize: 30, color: Colors.brandGreen },
  kpiLoading: { alignSelf: 'flex-start', marginVertical: 10 },
  kpiSub: { fontSize: 12, color: Colors.secondary, marginTop: 4 },
  columns: { gap: 28, marginTop: 28 },
  columnsWide: { flexDirection: 'row', alignItems: 'flex-start' },
  colMain: { flex: 1.6, minWidth: 0 },
  colSide: { flex: 1, minWidth: 0 },
  sectionGap: { marginTop: 28 },
});
