import { StyleSheet, Platform, Dimensions } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
  },
  loadingText: {
    marginTop: 16,
    color: '#64748B',
    fontSize: 14,
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
    backgroundColor: '#F8FAFC',
  },
  errorIcon: {
    fontSize: 48,
    marginBottom: 16,
  },
  errorText: {
    fontSize: 15,
    color: '#64748B',
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 24,
  },
  retryButton: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    backgroundColor: '#15803D',
    borderRadius: 8,
  },
  retryButtonText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 15,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 20,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  avatarCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#15803D',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  avatarText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 16,
  },
  welcomeText: {
    fontSize: 12,
    color: '#94A3B8',
  },
  userName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#0F172A',
  },
  logoutButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  logoutButtonText: {
    fontSize: 12,
    color: '#64748B',
    fontWeight: '500',
  },
  scrollContainer: {
    paddingHorizontal: 24,
    paddingVertical: 20,
  },
  badgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
  },
  badge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    marginRight: 10,
  },
  patientBadge: {
    backgroundColor: '#DCFCE7',
  },
  doctorBadge: {
    backgroundColor: '#DBEAFE',
  },
  badgeText: {
    fontSize: 12,
    fontWeight: 'bold',
  },
  patientBadgeText: {
    color: '#15803D',
  },
  doctorBadgeText: {
    color: '#1D4ED8',
  },
  emailText: {
    fontSize: 13,
    color: '#64748B',
  },
  promoCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#0F172A',
    borderRadius: 16,
    padding: 20,
    marginBottom: 28,
  },
  promoLeft: {
    flex: 1,
    marginRight: 16,
  },
  promoTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  promoDesc: {
    fontSize: 12,
    color: '#94A3B8',
    lineHeight: 16,
  },
  promoButton: {
    backgroundColor: '#15803D',
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 10,
  },
  promoButtonText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 13,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: 'bold',
    color: '#0F172A',
    marginBottom: 16,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 28,
  },
  gridCard: {
    width: '48%',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 16,
    padding: 16,
  },
  gridIcon: {
    fontSize: 24,
    marginBottom: 8,
  },
  gridLabel: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#0F172A',
    marginBottom: 2,
  },
  gridSub: {
    fontSize: 11,
    color: '#94A3B8',
  },
  timelineCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 16,
    padding: 20,
    paddingBottom: 4,
    marginBottom: 20,
  },
  timelineItem: {
    flexDirection: 'row',
    marginBottom: 16,
    position: 'relative',
  },
  lastTimelineItem: {
    marginBottom: 10,
  },
  timelineBullet: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#15803D',
    marginTop: 4,
    marginRight: 16,
    zIndex: 2,
  },
  emptyBullet: {
    backgroundColor: '#E2E8F0',
  },
  timelineContent: {
    flex: 1,
  },
  timelineTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#334155',
  },
  timelineTime: {
    fontSize: 11,
    color: '#94A3B8',
    marginTop: 2,
  },
  // Doctor Styles
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 28,
  },
  statCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
  },
  statVal: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#15803D',
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 10,
    color: '#64748B',
    fontWeight: '500',
  },
  queueContainer: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 16,
    padding: 12,
    marginBottom: 28,
  },
  queueItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  lastQueueItem: {
    borderBottomWidth: 0,
  },
  queueLeft: {
    flex: 1,
    marginRight: 12,
  },
  patientName: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#0F172A',
    marginBottom: 2,
  },
  queueDetails: {
    fontSize: 11,
    color: '#64748B',
  },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
  },
  statusWarn: {
    backgroundColor: '#FEF3C7',
  },
  statusOk: {
    backgroundColor: '#D1FAE5',
  },
  statusDanger: {
    backgroundColor: '#FEE2E2',
  },
  statusText: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#374151',
  },
  clinicLinkRow: {
    marginBottom: 10,
    alignSelf: 'flex-start',
  },
  clinicLinkText: {
    fontSize: 14,
    color: '#15803D',
    fontWeight: 'bold',
  },
  desktopRow: {
    flexDirection: 'row',
    gap: 20,
    width: '100%',
  },
  mobileColumn: {
    flexDirection: 'column',
    width: '100%',
  },
  patientMainColumn: {
    flex: 2,
  },
  patientSideColumn: {
    flex: 1.2,
  },
  doctorMainColumn: {
    flex: 2,
  },
  doctorSideColumn: {
    flex: 1,
  },
  fullWidth: {
    width: '100%',
  },
  desktopGreeting: {
    marginBottom: 20,
  },
  greetingTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#0F172A',
  },
  greetingSubtitle: {
    fontSize: 13,
    color: '#166534',
    marginTop: 4,
  },
  metricsContainer: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 20,
  },
  metricCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 16,
    padding: 16,
  },
  metricHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  metricIconBox: {
    width: 32,
    height: 32,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  metricEmoji: {
    fontSize: 16,
  },
  metricBadge: {
    backgroundColor: '#F0FDF4',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
  },
  metricBadgeText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#166534',
  },
  metricLabel: {
    fontSize: 11,
    color: '#64748B',
    marginTop: 8,
  },
  metricValue: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#0F172A',
    marginTop: 2,
  },
  metricUnit: {
    fontSize: 12,
    fontWeight: 'normal',
    color: '#64748B',
  },
  sparkline: {
    flexDirection: 'row',
    gap: 2,
    alignItems: 'flex-end',
    height: 30,
    marginTop: 10,
  },
  sparklineBar: {
    flex: 1,
    borderRadius: 2,
  },
  barContainer: {
    height: 6,
    backgroundColor: '#F1F5F9',
    borderRadius: 3,
    marginTop: 14,
    overflow: 'hidden',
  },
  barFill: {
    height: '100%',
    borderRadius: 3,
  },
  metricBadgeValue: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#334155',
  },
  mriCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 16,
    overflow: 'hidden',
    marginBottom: 20,
  },
  mriRowLayout: {
    flexDirection: 'row',
  },
  mriColumnLayout: {
    flexDirection: 'column',
  },
  mriImageContainerDesktop: {
    width: '40%',
    minHeight: 220,
    position: 'relative',
    backgroundColor: '#090D16',
  },
  mriImageContainerMobile: {
    width: '100%',
    height: 200,
    position: 'relative',
    backgroundColor: '#090D16',
  },
  mriImage: {
    width: '100%',
    height: '100%',
  },
  aiOverlayBadge: {
    position: 'absolute',
    bottom: 12,
    left: 12,
    backgroundColor: '#15803D',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  aiDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#FFFFFF',
  },
  aiOverlayText: {
    color: '#FFFFFF',
    fontSize: 9,
    fontWeight: 'bold',
  },
  mriInfoContainer: {
    flex: 1,
    padding: 20,
  },
  mriHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  mriIdText: {
    fontSize: 11,
    fontFamily: 'monospace',
    color: '#64748B',
    backgroundColor: '#F1F5F9',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  mriTimeText: {
    fontSize: 11,
    color: '#94A3B8',
  },
  mriTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#0F172A',
    marginBottom: 6,
  },
  mriDesc: {
    fontSize: 12,
    color: '#64748B',
    lineHeight: 18,
    marginBottom: 16,
  },
  mriSpecsGrid: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  mriSpecBox: {
    flex: 1,
    backgroundColor: '#F8FAFC',
    borderRadius: 10,
    padding: 10,
  },
  mriSpecLabel: {
    fontSize: 9,
    color: '#94A3B8',
    fontWeight: 'bold',
    marginBottom: 2,
  },
  mriSpecValue: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#334155',
  },
  mriReportBtn: {
    backgroundColor: '#15803D',
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
  },
  mriReportBtnText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: 'bold',
  },
  sideCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
  },
  sideCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  sideCardTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#0F172A',
  },
  sideCardLink: {
    fontSize: 12,
    color: '#15803D',
    fontWeight: 'bold',
  },
  scheduleList: {
    gap: 12,
  },
  scheduleItem: {
    flexDirection: 'row',
    gap: 12,
  },
  scheduleTimeline: {
    alignItems: 'center',
    width: 12,
  },
  timelineDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginTop: 4,
  },
  timelineLine: {
    width: 1,
    flex: 1,
    backgroundColor: '#F1F5F9',
    marginTop: 4,
  },
  scheduleContent: {
    flex: 1,
    paddingBottom: 12,
  },
  scheduleTime: {
    fontSize: 11,
    color: '#94A3B8',
    fontWeight: '500',
  },
  scheduleTitle: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#334155',
    marginTop: 2,
  },
  scheduleDesc: {
    fontSize: 11,
    color: '#64748B',
    marginTop: 2,
    lineHeight: 15,
  },
  scheduleTags: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 8,
    flexWrap: 'wrap',
  },
  scheduleTag: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
    backgroundColor: '#F1F5F9',
  },
  scheduleTagText: {
    fontSize: 10,
    color: '#475569',
    fontWeight: '500',
  },
  tagSuccess: {
    backgroundColor: '#DCFCE7',
  },
  tagSuccessText: {
    color: '#15803D',
  },
  tagInfo: {
    backgroundColor: '#EFF6FF',
    borderWidth: 1,
    borderColor: '#DBEAFE',
  },
  tagInfoText: {
    color: '#1D4ED8',
  },
  aiChatCard: {
    backgroundColor: '#0F172A',
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
  },
  aiChatHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  aiChatStatusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#4ADE80',
  },
  aiChatTitle: {
    color: '#4ADE80',
    fontSize: 10,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  aiChatQuestion: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 12,
  },
  aiChatQuote: {
    backgroundColor: '#1E293B',
    borderRadius: 10,
    padding: 10,
    marginBottom: 12,
  },
  aiChatQuoteText: {
    color: '#CBD5E1',
    fontSize: 11,
    fontStyle: 'italic',
    lineHeight: 15,
  },
  aiChatBtn: {
    backgroundColor: '#15803D',
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 6,
  },
  aiChatBtnText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: 'bold',
  },
  doctorStatsRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 20,
  },
  doctorStatCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
  },
  doctorStatVal: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#15803D',
    marginBottom: 4,
  },
  doctorStatLabel: {
    fontSize: 10,
    color: '#64748B',
    fontWeight: '500',
  },
  queueCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 16,
    paddingHorizontal: 16,
    marginBottom: 20,
  },
  queueItemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  lastQueueItemRow: {
    borderBottomWidth: 0,
  },
  queueLeftInfo: {
    flex: 1,
    marginRight: 12,
  },
  queuePatientName: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#0F172A',
    marginBottom: 2,
  },
  queueDetailsText: {
    fontSize: 11,
    color: '#64748B',
  },
  doctorGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 20,
  },
  doctorGridCard: {
    width: '47%',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    padding: 12,
  },
  doctorGridIcon: {
    fontSize: 20,
    marginBottom: 6,
  },
  doctorGridLabel: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#0F172A',
  },
  doctorGridSub: {
    fontSize: 10,
    color: '#94A3B8',
    marginTop: 2,
  },
  researchCard: {
    backgroundColor: '#0F172A',
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
  },
  researchCategory: {
    fontSize: 9,
    fontWeight: 'bold',
    color: '#4ADE80',
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  researchTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 12,
  },
  researchLink: {
    fontSize: 12,
    color: '#4ADE80',
    fontWeight: '600',
  },
});
