import { StyleSheet, Platform, Dimensions } from 'react-native';
import Colors from '../constants/colors';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
  },
  loadingText: {
    marginTop: 16,
    color: '#64748B',
    fontSize: 14,
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
    backgroundColor: '#F8FAFC',
  },
  errorIcon: {
    fontSize: 48,
    marginBottom: 16,
  },
  errorText: {
    fontSize: 15,
    color: '#64748B',
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 24,
  },
  retryButton: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    backgroundColor: '#0891B2',
    borderRadius: 8,
  },
  retryButtonText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 15,
  },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12, paddingHorizontal: 16, paddingVertical: 14, backgroundColor: Colors.surface, borderBottomWidth: 1, borderBottomColor: Colors.border },
  headerNameBox: { flex: 1, minWidth: 0 },
  headerLeft: { flexDirection: 'row', alignItems: 'center', flex: 1, minWidth: 0 },
  avatarCircle: { width: 40, height: 40, borderRadius: 20, backgroundColor: Colors.brandNavy, justifyContent: 'center', alignItems: 'center', marginRight: 10 },
  avatarText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 16,
  },
  welcomeText: { fontSize: 12, color: Colors.secondary },
  userName: { fontSize: 15, fontWeight: '700', color: Colors.brandNavy },
  logoutButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  logoutButtonText: { fontSize: 13, color: Colors.slateMuted, fontWeight: '500' },
  scrollContainer: {
    paddingHorizontal: 24,
    paddingVertical: 20,
  },
  badgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
  },
  badge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    marginRight: 10,
  },
  patientBadge: {
    backgroundColor: '#DCFCE7',
  },
  doctorBadge: { backgroundColor: Colors.brandGreenSoft },
  badgeText: {
    fontSize: 12,
    fontWeight: 'bold',
  },
  patientBadgeText: {
    color: '#059669',
  },
  doctorBadgeText: { color: Colors.brandGreen },
  emailText: { fontSize: 13, color: Colors.secondary },
  sectionTitle: { fontSize: 18, fontWeight: '700', color: Colors.brandNavy, marginBottom: 12 },
  gridIcon: {
    fontSize: 24,
    marginBottom: 8,
  },
  timelineCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 16,
    padding: 20,
    paddingBottom: 4,
    marginBottom: 20,
  },
  timelineItem: {
    flexDirection: 'row',
    marginBottom: 16,
    position: 'relative',
  },
  lastTimelineItem: {
    marginBottom: 10,
  },
  timelineBullet: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#0891B2',
    marginTop: 4,
    marginRight: 16,
    zIndex: 2,
  },
  emptyBullet: {
    backgroundColor: '#E2E8F0',
  },
  timelineContent: {
    flex: 1,
  },
  timelineTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#334155',
  },
  timelineTime: {
    fontSize: 11,
    color: '#94A3B8',
    marginTop: 2,
  },
  // Doctor Styles
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 28,
  },
  statCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
  },
  statVal: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#0891B2',
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 10,
    color: '#64748B',
    fontWeight: '500',
  },
  queueContainer: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 16,
    padding: 12,
    marginBottom: 28,
  },
  queueItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  lastQueueItem: {
    borderBottomWidth: 0,
  },
  queueLeft: {
    flex: 1,
    marginRight: 12,
  },
  patientName: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#0F172A',
    marginBottom: 2,
  },
  queueDetails: {
    fontSize: 11,
    color: '#64748B',
  },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
  },
  statusWarn: {
    backgroundColor: '#FEF3C7',
  },
  statusOk: {
    backgroundColor: '#D1FAE5',
  },
  statusDanger: {
    backgroundColor: '#FEE2E2',
  },
  statusText: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#374151',
  },
  statusBadgeText: { fontSize: 12, fontWeight: '700', color: '#374151' },
  clinicLinkRow: {
    marginBottom: 10,
    alignSelf: 'flex-start',
  },
  clinicLinkText: {
    fontSize: 14,
    color: '#0891B2',
    fontWeight: 'bold',
  },
  desktopRow: {
    flexDirection: 'row',
    gap: 20,
    width: '100%',
  },
  mobileColumn: {
    flexDirection: 'column',
    width: '100%',
  },
  doctorMainColumn: {
    flex: 2,
  },
  doctorSideColumn: {
    flex: 1,
  },
  fullWidth: {
    width: '100%',
  },
  desktopGreeting: {
    marginBottom: 20,
  },
  greetingTitle: { fontSize: 24, fontWeight: '800', color: Colors.brandNavy, letterSpacing: -0.3 },
  greetingSubtitle: { fontSize: 14, color: Colors.slateMuted, marginTop: 4, lineHeight: 20 },
  metricsContainer: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 20,
  },
  metricCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 16,
    padding: 16,
  },
  metricHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  metricIconBox: {
    width: 32,
    height: 32,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  metricEmoji: {
    fontSize: 16,
  },
  metricBadge: {
    backgroundColor: '#F0FDF4',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
  },
  metricBadgeText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#166534',
  },
  metricLabel: {
    fontSize: 11,
    color: '#64748B',
    marginTop: 8,
  },
  metricValue: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#0F172A',
    marginTop: 2,
  },
  metricUnit: {
    fontSize: 12,
    fontWeight: 'normal',
    color: '#64748B',
  },
  sparkline: {
    flexDirection: 'row',
    gap: 2,
    alignItems: 'flex-end',
    height: 30,
    marginTop: 10,
  },
  sparklineBar: {
    flex: 1,
    borderRadius: 2,
  },
  barContainer: {
    height: 6,
    backgroundColor: '#F1F5F9',
    borderRadius: 3,
    marginTop: 14,
    overflow: 'hidden',
  },
  barFill: {
    height: '100%',
    borderRadius: 3,
  },
  metricBadgeValue: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#334155',
  },
  emptyMriIcon: {
    fontSize: 36,
    marginBottom: 12,
  },
  doctorStatsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginBottom: 20 },
  doctorStatCard: { flex: 1, minWidth: 120, backgroundColor: Colors.surface, borderWidth: 1, borderColor: Colors.border, borderRadius: 14, paddingVertical: 16, paddingHorizontal: 16, boxShadow: '0 1px 2px rgba(11, 42, 85, 0.05)' },
  doctorStatVal: { fontSize: 24, fontWeight: '800', color: Colors.brandNavy, marginBottom: 2, fontVariant: ['tabular-nums'] },
  doctorStatLabel: { fontSize: 13, color: Colors.slateMuted, fontWeight: '500' },
  queueCard: { backgroundColor: Colors.surface, borderWidth: 1, borderColor: Colors.border, borderRadius: 14, paddingHorizontal: 16, marginBottom: 20 },
  queueItemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  lastQueueItemRow: {
    borderBottomWidth: 0,
  },
  queueLeftInfo: {
    flex: 1,
    marginRight: 12,
  },
  queuePatientName: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#0F172A',
    marginBottom: 2,
  },
  queueDetailsText: {
    fontSize: 11,
    color: '#64748B',
  },
  doctorGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 20,
  },
  doctorGridCard: { width: '47%', backgroundColor: Colors.surface, borderWidth: 1, borderColor: Colors.border, borderRadius: 14, padding: 14 },
  doctorGridIcon: {
    fontSize: 20,
    marginBottom: 6,
  },
  doctorGridLabel: { fontSize: 14, fontWeight: '700', color: Colors.brandNavy },
  doctorGridSub: { fontSize: 12, color: Colors.secondary, marginTop: 2, lineHeight: 17 },
  researchCard: { backgroundColor: Colors.brandNavy, borderRadius: 16, padding: 18, marginBottom: 20 },
  researchCategory: { fontSize: 12, fontWeight: '700', color: Colors.brandMint, letterSpacing: 0.4, marginBottom: 6 },
  researchTitle: { fontSize: 15, fontWeight: '700', color: '#FFFFFF', marginBottom: 12 },
  researchLink: { fontSize: 13, color: Colors.brandMint, fontWeight: '600' },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 24,
    width: '100%',
    maxWidth: 440,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 5,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#0F172A',
    marginBottom: 6,
  },
  modalSub: {
    fontSize: 12,
    color: '#64748B',
    marginBottom: 20,
  },
  field: {
    marginBottom: 16,
  },
  label: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#475569',
    marginBottom: 6,
  },
  input: {
    height: 42,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 8,
    paddingHorizontal: 12,
    fontSize: 14,
    backgroundColor: '#F8FAFC',
    color: '#0F172A',
  },
  modalButtonRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
    marginTop: 8,
  },
  btnCancel: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  btnCancelText: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#64748B',
  },
  btnSave: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    backgroundColor: '#059669',
  },
  btnSaveText: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  editProfileTrigger: { marginTop: 4, paddingVertical: 2, alignSelf: 'flex-start' },
  editProfileTriggerText: { fontSize: 13, color: Colors.brandGreen, fontWeight: '600' },
});
