import { StyleSheet } from 'react-native';
import Colors from '../constants/colors';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },

  page: { padding: 16, gap: 20 },
  pageDesktop: { padding: 28, gap: 24, maxWidth: 1240, width: '100%', alignSelf: 'center' },

  refreshBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    height: 40,
    paddingHorizontal: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.surface,
  },
  refreshBtnHover: { borderColor: Colors.brandGreen, backgroundColor: Colors.brandGreenSoft },
  refreshBtnText: { fontSize: 14, fontWeight: '600', color: Colors.brandGreen },
  refreshBtnOnDark: { borderColor: 'rgba(164, 251, 229, 0.45)', backgroundColor: 'rgba(255, 255, 255, 0.08)' },
  refreshBtnOnDarkHover: { backgroundColor: 'rgba(164, 251, 229, 0.16)', borderColor: Colors.brandMint },
  refreshBtnTextOnDark: { color: Colors.brandMint },

  columns: { gap: 20 },
  columnsDesktop: { flexDirection: 'row', alignItems: 'flex-start', gap: 24 },
  list: { gap: 14 },
  listCol: { flex: 1.7 },
  asideCol: { flex: 1, maxWidth: 380 },

  // Thẻ hướng dẫn chuẩn bị chụp
  prepCard: {
    backgroundColor: Colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors.border,
    padding: 20,
    boxShadow: '0 1px 2px rgba(11, 42, 85, 0.05)',
  },
  prepIllus: { width: 150, height: 150, alignSelf: 'center', marginTop: -18, marginBottom: -6 },
  prepTitle: { fontSize: 17, fontWeight: '700', color: Colors.brandNavy, lineHeight: 23, marginBottom: 6 },
  prepRow: { flexDirection: 'row', gap: 10, marginTop: 10 },
  prepCheck: { width: 22, height: 22, borderRadius: 11, backgroundColor: Colors.brandGreenSoft, alignItems: 'center', justifyContent: 'center', marginTop: 1 },
  prepText: { flex: 1, fontSize: 14, lineHeight: 20, color: Colors.slateDark },
  prepDivider: { height: 1, backgroundColor: Colors.border, marginVertical: 16 },
  prepHint: { fontSize: 14, color: Colors.slateMuted },
  prepBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    height: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.brandGreen,
    marginTop: 10,
  },
  prepBtnHover: { backgroundColor: Colors.brandGreenSoft },
  prepBtnText: { fontSize: 15, fontWeight: '700', color: Colors.brandGreen },

  card: {
    backgroundColor: Colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors.border,
    overflow: 'hidden',
    boxShadow: '0 1px 2px rgba(15, 23, 42, 0.05)',
  },
  cardHover: {
    borderColor: Colors.brandGreen,
    boxShadow: '0 10px 24px -12px rgba(11, 42, 85, 0.30)',
  },
  cardInner: { flexDirection: 'row' },
  thumbWrap: { width: 132, minHeight: 148, backgroundColor: '#05101F', position: 'relative' },
  thumb: { width: '100%', height: '100%', minHeight: 148 },
  typeChip: {
    position: 'absolute',
    top: 10,
    left: 10,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    borderWidth: 1,
  },
  typeChipMri: { backgroundColor: 'rgba(11, 42, 85, 0.85)', borderColor: 'rgba(164, 251, 229, 0.4)' },
  typeChipCt: { backgroundColor: 'rgba(3, 105, 161, 0.85)', borderColor: 'rgba(255, 255, 255, 0.35)' },
  typeChipText: { color: '#FFFFFF', fontSize: 12, fontWeight: '700', letterSpacing: 0.4 },

  cardBody: { flex: 1, padding: 16 },
  dateText: { fontSize: 13, color: Colors.secondary, fontVariant: ['tabular-nums'] },
  procedureTitle: { fontSize: 16, fontWeight: '700', color: Colors.brandNavy, marginTop: 4, lineHeight: 22 },
  conclusionText: { fontSize: 14, color: Colors.slateDark, lineHeight: 20, marginTop: 8 },
  conclusionLabel: { fontWeight: '600', color: Colors.slateMuted },
  cardFooter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, marginTop: 12 },
  doctorText: { flex: 1, fontSize: 13, color: Colors.secondary },
  openLink: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  openLinkText: { fontSize: 14, fontWeight: '700', color: Colors.brandGreen },

  skeleton: { backgroundColor: '#E8EDF3', borderRadius: 8 },

  stateIllus: { width: 160, height: 160, marginBottom: 4 },
  stateBox: {
    alignSelf: 'center',
    maxWidth: 520,
    width: '100%',
    alignItems: 'center',
    padding: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: Colors.borderStrong,
    backgroundColor: Colors.surface,
  },
  stateIcon: { width: 48, height: 48, borderRadius: 24, backgroundColor: Colors.brandGreenSoft, alignItems: 'center', justifyContent: 'center', marginBottom: 12 },
  stateIconWarn: { backgroundColor: Colors.warningBg },
  stateTitle: { fontSize: 16, fontWeight: '700', color: Colors.brandNavy },
  stateText: { fontSize: 14, color: Colors.secondary, textAlign: 'center', marginTop: 4, lineHeight: 20 },
  retryBtn: { marginTop: 16, height: 44, paddingHorizontal: 20, borderRadius: 10, backgroundColor: Colors.brandGreen, justifyContent: 'center' },
  retryBtnHover: { backgroundColor: Colors.brandGreenPressed },
  retryBtnText: { color: '#FFFFFF', fontSize: 15, fontWeight: '700' },
});
