import Colors from '../constants/colors';
import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F1F5F9',
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  loadingText: {
    marginTop: 12,
    color: '#64748B',
    fontSize: 14,
  },
  errorIcon: {
    fontSize: 48,
    marginBottom: 16,
  },
  errorText: {
    fontSize: 15,
    color: '#64748B',
    textAlign: 'center',
    marginBottom: 20,
  },
  backBtn: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    backgroundColor: '#15803D',
    borderRadius: 8,
  },
  backBtnText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 14,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  backArrowBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    height: 36,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  backArrowBtnHover: { backgroundColor: '#F1F5F9' },
  backArrowText: {
    fontSize: 14,
    fontWeight: '600',
    color: Colors.brandNavy,
  },
  actionBar: { flexDirection: 'row', gap: 10, marginBottom: 20, flexWrap: 'wrap', justifyContent: 'flex-end' },
  actionPrimary: {
    flexDirection: 'row', alignItems: 'center', gap: 8, height: 42, paddingHorizontal: 16, borderRadius: 10,
    backgroundColor: Colors.brandGreen, boxShadow: '0 6px 14px -6px rgba(6, 122, 94, 0.45)',
  },
  actionPrimaryHover: { backgroundColor: Colors.brandGreenPressed },
  actionPrimaryText: { color: '#FFFFFF', fontWeight: '700', fontSize: 14 },
  actionSecondary: {
    flexDirection: 'row', alignItems: 'center', gap: 8, height: 42, paddingHorizontal: 16, borderRadius: 10,
    borderWidth: 1, borderColor: Colors.brandGreen, backgroundColor: Colors.surface,
  },
  actionSecondaryHover: { backgroundColor: Colors.brandGreenSoft },
  actionSecondaryText: { color: Colors.brandGreen, fontWeight: '700', fontSize: 14 },
  explainCard: {
    marginTop: 20, borderRadius: 14, padding: 18, backgroundColor: Colors.brandNavy, overflow: 'hidden',
  },
  explainHeader: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  explainIcon: {
    width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center',
    backgroundColor: 'rgba(164, 251, 229, 0.12)', borderWidth: 1, borderColor: 'rgba(164, 251, 229, 0.3)',
  },
  explainTitle: { color: '#FFFFFF', fontSize: 16, fontWeight: '700' },
  explainSub: { color: '#B9C9E0', fontSize: 13, marginTop: 2 },
  explainBtn: {
    marginTop: 16, alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 8,
    height: 42, paddingHorizontal: 18, borderRadius: 10, backgroundColor: Colors.brandMint,
  },
  explainBtnHover: { backgroundColor: '#C6FFF0' },
  explainBtnText: { color: Colors.brandNavy, fontSize: 15, fontWeight: '700' },
  explainBody: { marginTop: 16 },
  explainNote: { color: '#B9C9E0', fontSize: 12, lineHeight: 18, marginTop: 12, fontStyle: 'italic' },
  explainLoading: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 16 },
  explainDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: Colors.brandMint },
  explainLoadingText: { color: '#D7E3F4', fontSize: 14, marginLeft: 6 },
  badge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
  },
  mriBadge: {
    backgroundColor: '#E8EEF7',
  },
  ctBadge: {
    backgroundColor: '#FFF7ED',
  },
  badgeText: {
    fontSize: 12,
    fontWeight: 'bold',
  },
  mriBadgeText: {
    color: Colors.brandNavy,
  },
  ctBadgeText: {
    color: '#EA580C',
  },
  scrollContainer: {
    padding: 16,
  },
  scrollContainerDesktop: {
    maxWidth: 900,
    width: '100%',
    alignSelf: 'center',
  },
  reportSheet: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 24,
    boxShadow: '0 1px 2px rgba(15, 23, 42, 0.05), 0 12px 32px -16px rgba(11, 42, 85, 0.18)',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  hospitalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 16,
    marginBottom: 24,
  },
  hospitalInfo: {
    flex: 1,
    minWidth: 240,
  },
  deptText: {
    fontSize: 12,
    color: '#64748B',
    fontWeight: '600',
  },
  hospitalName: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#0F172A',
    marginTop: 2,
  },
  recordMeta: {
    alignItems: 'flex-end',
  },
  metaLabelText: {
    fontSize: 13,
    color: '#64748B',
    marginBottom: 2,
  },
  metaValText: {
    fontWeight: 'bold',
    color: '#0F172A',
  },
  sheetTitle: {
    fontSize: 18,
    fontWeight: '800',
    textAlign: 'center',
    color: Colors.brandNavy,
    marginVertical: 20,
    letterSpacing: 0.5,
  },
  patientGrid: {
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 8,
    padding: 14,
    backgroundColor: '#F8FAFC',
  },
  gridRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 10,
  },
  gridCell: {
    flex: 1,
    minWidth: 120,
  },
  fieldLabel: {
    fontSize: 12,
    color: Colors.secondary,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  fieldVal: {
    fontSize: 14,
    color: '#334155',
    fontWeight: '500',
  },
  fieldValBold: {
    fontSize: 14,
    color: '#0F172A',
    fontWeight: '700',
  },
  sectionDivider: {
    height: 1,
    backgroundColor: '#E2E8F0',
    marginVertical: 20,
  },
  detailSection: {
    paddingVertical: 4,
  },
  sectionHeading: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#64748B',
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  headingBodyBold: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#0F172A',
    lineHeight: 22,
  },
  headingBody: {
    fontSize: 14,
    color: '#334155',
    lineHeight: 22,
  },
  gallerySection: {
    paddingVertical: 4,
  },
  carouselContainer: {
    alignItems: 'center',
    marginTop: 12,
  },
  mainImageWrapper: {
    width: '100%',
    height: 320,
    backgroundColor: '#000000',
    borderRadius: 12,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  mainImage: {
    width: '100%',
    height: '100%',
  },
  zoomOverlayIcon: {
    position: 'absolute',
    bottom: 12,
    right: 12,
    backgroundColor: 'rgba(15, 23, 42, 0.75)',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
  },
  zoomOverlayText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: 'bold',
  },
  imageCounter: {
    fontSize: 13,
    color: '#64748B',
    marginTop: 10,
    fontWeight: '500',
  },
  thumbnailList: {
    paddingVertical: 12,
    gap: 8,
  },
  thumbnailWrapper: {
    width: 60,
    height: 60,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: '#000000',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  activeThumbnailWrapper: {
    borderColor: '#15803D',
  },
  thumbnailImage: {
    width: '100%',
    height: '100%',
  },
  findingsSection: {
    paddingVertical: 4,
  },
  findingsBody: {
    fontSize: 15,
    color: '#334155',
    lineHeight: 24,
  },
  conclusionBox: {
    marginTop: 20,
    backgroundColor: Colors.brandGreenSoft,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#CDEBDF',
  },
  conclusionHeading: {
    fontSize: 12,
    fontWeight: 'bold',
    color: Colors.brandGreen,
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  conclusionBody: {
    fontSize: 16,
    fontWeight: '600',
    color: '#0F172A',
    lineHeight: 22,
  },
  signatureSection: {
    alignItems: 'flex-end',
    marginTop: 30,
    paddingRight: 12,
  },
  signDate: {
    fontSize: 13,
    color: '#64748B',
    fontStyle: 'italic',
    marginBottom: 4,
  },
  signTitle: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#0F172A',
    marginBottom: 10,
  },
  stampBox: {
    borderWidth: 2,
    borderColor: '#DC2626',
    borderRadius: 4,
    padding: 8,
    backgroundColor: 'rgba(254, 226, 226, 0.4)',
    alignItems: 'center',
    marginBottom: 10,
    transform: [{ rotate: '-2deg' }],
  },
  stampText: {
    color: '#DC2626',
    fontWeight: '900',
    fontSize: 13,
  },
  stampDoctor: {
    color: '#DC2626',
    fontWeight: '700',
    fontSize: 12,
    marginTop: 2,
  },
  stampTime: {
    color: '#991B1B',
    fontSize: 9,
    marginTop: 2,
  },
  signDoctorName: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#0F172A',
    marginTop: 10,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.95)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeModalBtn: {
    position: 'absolute',
    top: 50,
    right: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    zIndex: 10,
  },
  closeModalBtnText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 13,
  },
  modalImageWrapper: {
    width: '90%',
    height: '70%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalImage: {
    width: '100%',
    height: '100%',
  },
  modalCounter: {
    color: '#94A3B8',
    fontSize: 14,
    marginTop: 20,
    fontWeight: '500',
  },
});
