import { StyleSheet, Platform, Dimensions } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8FAFC' },
  centerState: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 24, gap: 12 },
  centerText: { fontSize: 14, color: '#64748B', textAlign: 'center' },
  errorIcon: { fontSize: 36 },
  retryBtn: { backgroundColor: '#15803D', borderRadius: 10, paddingHorizontal: 20, paddingVertical: 10 },
  retryBtnText: { color: '#FFF', fontWeight: '600' },
  header: {
    flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 14,
    backgroundColor: '#FFFFFF', borderBottomWidth: 1, borderBottomColor: '#E2E8F0',
  },
  backButton: { paddingVertical: 4, marginRight: 16 },
  backButtonText: { fontSize: 14, color: '#64748B', fontWeight: '500' },
  headerTitle: { fontSize: 18, fontWeight: 'bold', color: '#0F172A' },
  scrollContainer: { paddingHorizontal: 16, paddingVertical: 16, paddingBottom: 40 },
  pageTitleBlock: { marginBottom: 16 },
  pageTitle: { fontSize: 20, fontWeight: 'bold', color: '#0F172A', marginBottom: 4 },
  pageSubtitle: { fontSize: 13, color: '#64748B', lineHeight: 19 },
  statsRow: { flexDirection: 'row', gap: 10, marginBottom: 16 },
  statCard: { flex: 1, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 12, paddingVertical: 12, alignItems: 'center' },
  statValue: { fontSize: 18, fontWeight: 'bold', color: '#0F172A' },
  statLabel: { fontSize: 10, color: '#64748B', marginTop: 2, textAlign: 'center' },
  identityCard: { backgroundColor: '#0F172A', borderRadius: 16, padding: 16, marginBottom: 16, gap: 10 },
  identityRow: { flexDirection: 'row', gap: 12 },
  identityField: { flex: 1 },
  identityLabel: { fontSize: 10, color: '#94A3B8', marginBottom: 2, fontWeight: '600' },
  identityValue: { fontSize: 13, color: '#FFFFFF', fontWeight: 'bold' },
  identityEditHint: { fontSize: 10, color: '#4ADE80', marginTop: 4 },
  searchContainer: {
    flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFFFFF',
    borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 12,
    paddingHorizontal: 12, height: 46, marginBottom: 20,
  },
  searchIcon: { fontSize: 14, marginRight: 8 },
  searchInput: { flex: 1, fontSize: 14, color: '#0F172A' },
  sectionTitle: { fontSize: 15, fontWeight: 'bold', color: '#0F172A', marginBottom: 14 },
  emptyState: { alignItems: 'center', paddingVertical: 32 },
  emptyIcon: { fontSize: 40, marginBottom: 12 },
  emptyText: { fontSize: 14, color: '#94A3B8', textAlign: 'center', lineHeight: 20 },
  timelineContainer: { gap: 0 },
  timelineItem: { flexDirection: 'row', gap: 12 },
  timelineBar: { width: 20, alignItems: 'center', paddingTop: 20 },
  timelineDot: { width: 14, height: 14, borderRadius: 7 },
  dotInpatient: { backgroundColor: '#EF4444' },
  dotOutpatient: { backgroundColor: '#2563EB' },
  timelineLine: { width: 2, flex: 1, backgroundColor: '#E2E8F0', marginTop: 4 },
  timelineCard: { flex: 1, paddingBottom: 16 },
  visitCard: { backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 14, overflow: 'hidden' },
  visitHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 14 },
  visitHeaderLeft: { flexDirection: 'row', gap: 10, flex: 1 },
  visitTypeBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6, alignSelf: 'flex-start' },
  badgeInpatient: { backgroundColor: '#FEE2E2' },
  badgeOutpatient: { backgroundColor: '#EFF6FF' },
  visitTypeText: { fontSize: 10, fontWeight: 'bold' },
  badgeInpatientText: { color: '#EF4444' },
  badgeOutpatientText: { color: '#2563EB' },
  visitMeta: { flex: 1 },
  visitDate: { fontSize: 13, fontWeight: 'bold', color: '#0F172A' },
  visitFacility: { fontSize: 12, color: '#64748B', marginTop: 1 },
  visitDiagnosis: { fontSize: 11, color: '#94A3B8', marginTop: 2 },
  visitHeaderRight: { alignItems: 'center', minWidth: 50 },
  visitDocCount: { fontSize: 16, fontWeight: 'bold', color: '#15803D' },
  visitDocCountLabel: { fontSize: 9, color: '#64748B' },
  visitToggle: { fontSize: 10, color: '#94A3B8', marginTop: 4 },
  visitBody: { borderTopWidth: 1, borderTopColor: '#F1F5F9', padding: 14, gap: 12 },
  visitInfoRow: { flexDirection: 'row', gap: 12 },
  visitInfoItem: { flex: 1 },
  visitInfoLabel: { fontSize: 10, color: '#94A3B8', marginBottom: 2 },
  visitInfoValue: { fontSize: 12, color: '#334155', fontWeight: '600' },
  progressContainer: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  progressBg: { flex: 1, height: 6, backgroundColor: '#F1F5F9', borderRadius: 3, overflow: 'hidden' },
  progressFill: { height: '100%', backgroundColor: '#15803D', borderRadius: 3 },
  progressText: { fontSize: 11, color: '#15803D', fontWeight: '600', minWidth: 60 },
  groupCard: { borderWidth: 1, borderRadius: 12, overflow: 'hidden' },
  groupHeader: { flexDirection: 'row', alignItems: 'center', padding: 10, gap: 8 },
  groupIcon: { fontSize: 16 },
  groupLabel: { flex: 1, fontSize: 12, fontWeight: 'bold' },
  groupCount: { fontSize: 11, fontWeight: '600' },
  groupToggle: { fontSize: 10, marginLeft: 4 },
  docList: { padding: 10, paddingTop: 0, gap: 8 },
  docCard: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: 12, paddingVertical: 10, borderRadius: 10, borderWidth: 1,
  },
  docCardHas: { backgroundColor: '#F0FDF4', borderColor: '#BBF7D0' },
  docCardMissing: { backgroundColor: '#FFFFFF', borderColor: '#E2E8F0', borderStyle: 'dashed' },
  docCardLeft: { flexDirection: 'row', gap: 10, flex: 1, alignItems: 'center' },
  docIcon: { fontSize: 16 },
  docInfo: { flex: 1 },
  docLabel: { fontSize: 12, color: '#334155', fontWeight: '500' },
  docLabelMissing: { color: '#94A3B8' },
  docStatusHas: { fontSize: 10, color: '#15803D', marginTop: 2 },
  docStatusMissing: { fontSize: 10, color: '#94A3B8', marginTop: 2 },
  deleteDocBtn: { paddingHorizontal: 6, paddingVertical: 4 },
  deleteDocBtnText: { fontSize: 14 },
  countBadge: {
    minWidth: 20, height: 20, borderRadius: 10, backgroundColor: '#15803D',
    alignItems: 'center', justifyContent: 'center', paddingHorizontal: 5, marginRight: 6,
  },
  countBadgeText: { fontSize: 11, color: '#FFF', fontWeight: 'bold' },
  deleteVisitBtn: { borderWidth: 1, borderColor: '#FCA5A5', borderRadius: 10, paddingVertical: 9, alignItems: 'center' },
  deleteVisitBtnText: { fontSize: 12, color: '#EF4444', fontWeight: '600' },
  addVisitBtn: { backgroundColor: '#15803D', borderRadius: 12, paddingVertical: 14, alignItems: 'center', marginTop: 8, marginBottom: 16 },
  addVisitBtnText: { fontSize: 14, color: '#FFFFFF', fontWeight: 'bold' },
  infoNote: { flexDirection: 'row', gap: 10, backgroundColor: '#F8FAFC', borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 12, padding: 12 },
  infoNoteIcon: { fontSize: 14 },
  infoNoteText: { flex: 1, fontSize: 11, color: '#64748B', lineHeight: 17 },
  modalContainer: { flex: 1, backgroundColor: '#F8FAFC' },
  modalHeader: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    paddingHorizontal: 16, paddingVertical: 14, backgroundColor: '#FFFFFF',
    borderBottomWidth: 1, borderBottomColor: '#E2E8F0',
  },
  modalTitle: { fontSize: 16, fontWeight: 'bold', color: '#0F172A' },
  modalCancel: { fontSize: 15, color: '#64748B' },
  modalSave: { fontSize: 15, color: '#15803D', fontWeight: 'bold' },
  modalBody: { padding: 16, paddingBottom: 40 },
  modalFieldLabel: { fontSize: 12, fontWeight: '600', color: '#334155', marginBottom: 6, marginTop: 14 },
  modalInput: {
    backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E2E8F0',
    borderRadius: 10, paddingHorizontal: 14, paddingVertical: 10, fontSize: 14, color: '#0F172A',
  },
  toggleRow: { flexDirection: 'row', gap: 10 },
  toggleBtn: { flex: 1, paddingVertical: 10, borderRadius: 10, borderWidth: 1, borderColor: '#E2E8F0', alignItems: 'center', backgroundColor: '#FFFFFF' },
  toggleBtnActive: { backgroundColor: '#DCFCE7', borderColor: '#15803D' },
  toggleBtnText: { fontSize: 14, color: '#64748B', fontWeight: '500' },
  toggleBtnTextActive: { color: '#15803D', fontWeight: 'bold' },
});
