import { StyleSheet, Platform } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8FAFC' },
  centerState: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 24, gap: 12 },
  centerText: { fontSize: 14, color: '#64748B', textAlign: 'center' },
  errorIcon: { fontSize: 36 },
  retryBtn: { backgroundColor: '#15803D', borderRadius: 10, paddingHorizontal: 20, paddingVertical: 10 },
  retryBtnText: { color: '#FFF', fontWeight: '600' },
  header: {
    flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 14,
    backgroundColor: '#FFFFFF', borderBottomWidth: 1, borderBottomColor: '#E2E8F0',
  },
  backButton: { paddingVertical: 4, marginRight: 16 },
  backButtonText: { fontSize: 14, color: '#64748B', fontWeight: '500' },
  headerTitle: { fontSize: 18, fontWeight: 'bold', color: '#0F172A' },
  scrollContainer: { paddingHorizontal: 16, paddingVertical: 16, paddingBottom: 40 },
  pageTitleBlock: { marginBottom: 16 },
  pageTitle: { fontSize: 22, fontWeight: 'bold', color: '#0F172A', marginBottom: 4 },
  pageSubtitle: { fontSize: 13, color: '#64748B', lineHeight: 19 },
  statsRow: { flexDirection: 'row', gap: 10, marginBottom: 16 },
  statCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    ...Platform.select({
      web: { boxShadow: '0 2px 6px rgba(0,0,0,0.03)' },
      default: { elevation: 1 },
    }),
  },
  statValue: { fontSize: 20, fontWeight: 'bold', color: '#0F172A' },
  statLabel: { fontSize: 11, color: '#64748B', marginTop: 2, textAlign: 'center', fontWeight: '500' },
  identityCard: {
    backgroundColor: '#0F172A',
    borderRadius: 18,
    padding: 18,
    marginBottom: 20,
    gap: 12,
    ...Platform.select({
      web: { boxShadow: '0 4px 12px rgba(15,23,42,0.15)' },
      default: { elevation: 3 },
    }),
  },
  identityRow: { flexDirection: 'row', gap: 12 },
  identityField: { flex: 1 },
  identityLabel: { fontSize: 10, color: '#94A3B8', marginBottom: 3, fontWeight: '600' },
  identityValue: { fontSize: 14, color: '#FFFFFF', fontWeight: 'bold' },
  identityEditHint: { fontSize: 11, color: '#4ADE80', marginTop: 4, fontWeight: '500' },
  searchContainer: {
    flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFFFFF',
    borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 12,
    paddingHorizontal: 12, height: 46, marginBottom: 20,
    ...Platform.select({
      web: { boxShadow: '0 1px 3px rgba(0,0,0,0.03)' },
      default: { elevation: 1 },
    }),
  },
  searchIcon: { fontSize: 14, marginRight: 8 },
  searchInput: { flex: 1, fontSize: 14, color: '#0F172A' },
  sectionTitle: { fontSize: 16, fontWeight: 'bold', color: '#0F172A', marginBottom: 14 },
  emptyState: { alignItems: 'center', paddingVertical: 32 },
  emptyIcon: { fontSize: 40, marginBottom: 12 },
  emptyText: { fontSize: 14, color: '#94A3B8', textAlign: 'center', lineHeight: 20 },
  timelineContainer: { gap: 0 },
  timelineItem: { flexDirection: 'row', gap: 12 },
  timelineBar: { width: 20, alignItems: 'center', paddingTop: 20 },
  timelineDot: { width: 14, height: 14, borderRadius: 7 },
  dotInpatient: { backgroundColor: '#EF4444' },
  dotOutpatient: { backgroundColor: '#2563EB' },
  timelineLine: { width: 2, flex: 1, backgroundColor: '#CBD5E1', marginTop: 4 },
  timelineCard: { flex: 1, paddingBottom: 16 },
  visitCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 16,
    overflow: 'hidden',
    ...Platform.select({
      web: { boxShadow: '0 2px 8px rgba(0,0,0,0.04)' },
      default: { elevation: 2 },
    }),
  },
  visitHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 16 },
  visitHeaderLeft: { flexDirection: 'row', gap: 12, flex: 1 },
  visitTypeBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8, alignSelf: 'flex-start' },
  badgeInpatient: { backgroundColor: '#FEE2E2' },
  badgeOutpatient: { backgroundColor: '#EFF6FF' },
  visitTypeText: { fontSize: 11, fontWeight: 'bold' },
  badgeInpatientText: { color: '#EF4444' },
  badgeOutpatientText: { color: '#2563EB' },
  visitMeta: { flex: 1 },
  visitDate: { fontSize: 14, fontWeight: 'bold', color: '#0F172A' },
  visitFacility: { fontSize: 12, color: '#64748B', marginTop: 2 },
  visitDiagnosis: { fontSize: 12, color: '#475569', marginTop: 3 },
  visitHeaderRight: { alignItems: 'center', minWidth: 55 },
  visitDocCount: { fontSize: 18, fontWeight: 'bold', color: '#15803D' },
  visitDocCountLabel: { fontSize: 10, color: '#64748B', fontWeight: '500' },
  visitToggle: { fontSize: 11, color: '#64748B', marginTop: 4, fontWeight: '600' },
  visitBody: { borderTopWidth: 1, borderTopColor: '#F1F5F9', padding: 16, gap: 14 },
  visitInfoRow: { flexDirection: 'row', gap: 12 },
  visitInfoItem: { flex: 1 },
  visitInfoLabel: { fontSize: 11, color: '#64748B', marginBottom: 2 },
  visitInfoValue: { fontSize: 13, color: '#1E293B', fontWeight: '600' },
  progressContainer: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  progressBg: { flex: 1, height: 8, backgroundColor: '#F1F5F9', borderRadius: 4, overflow: 'hidden' },
  progressFill: { height: '100%', backgroundColor: '#15803D', borderRadius: 4 },
  progressText: { fontSize: 12, color: '#15803D', fontWeight: 'bold', minWidth: 65 },
  groupCard: { borderWidth: 1, borderRadius: 14, overflow: 'hidden' },
  groupHeader: { flexDirection: 'row', alignItems: 'center', padding: 12, gap: 10 },
  groupIcon: { fontSize: 18 },
  groupLabel: { flex: 1, fontSize: 13, fontWeight: 'bold' },
  groupCount: { fontSize: 12, fontWeight: '600' },
  groupToggle: { fontSize: 11, marginLeft: 4 },
  docList: { padding: 12, paddingTop: 0, gap: 8 },
  docCard: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: 14, paddingVertical: 12, borderRadius: 12, borderWidth: 1,
  },
  docCardHas: { backgroundColor: '#F0FDF4', borderColor: '#BBF7D0' },
  docCardMissing: { backgroundColor: '#FFFFFF', borderColor: '#E2E8F0', borderStyle: 'dashed' },
  docCardLeft: { flexDirection: 'row', gap: 12, flex: 1, alignItems: 'center' },
  docIcon: { fontSize: 18 },
  docInfo: { flex: 1 },
  docLabel: { fontSize: 13, color: '#1E293B', fontWeight: '600' },
  docLabelMissing: { color: '#94A3B8' },
  docStatusHas: { fontSize: 11, color: '#15803D', marginTop: 2, fontWeight: '500' },
  docStatusMissing: { fontSize: 11, color: '#94A3B8', marginTop: 2 },
  countBadge: {
    minWidth: 22, height: 22, borderRadius: 11, backgroundColor: '#15803D',
    alignItems: 'center', justifyContent: 'center', paddingHorizontal: 6, marginRight: 6,
  },
  countBadgeText: { fontSize: 11, color: '#FFF', fontWeight: 'bold' },
  infoNote: { flexDirection: 'row', gap: 12, backgroundColor: '#F8FAFC', borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 14, padding: 14 },
  infoNoteIcon: { fontSize: 16 },
  infoNoteText: { flex: 1, fontSize: 12, color: '#475569', lineHeight: 18 },
});
