import Colors from '../constants/colors';
import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  backButton: {
    paddingVertical: 4,
    marginRight: 16,
  },
  backButtonText: {
    fontSize: 14,
    color: '#64748B',
    fontWeight: '500',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#0F172A',
  },
  scrollContainer: {
    paddingHorizontal: 16,
    paddingVertical: 24,
    maxWidth: 980,
    width: '100%',
    alignSelf: 'center',
  },
  bannerContainer: { marginBottom: 24 },

  plansContainer: {
    gap: 16,
    marginBottom: 28,
  },
  plansContainerDesktop: { flexDirection: 'row', alignItems: 'stretch', gap: 20 },
  planCardDesktop: { flex: 1, padding: 28 },
  featuresGrow: { flexGrow: 1 }, // đẩy nút xuống đáy để nút 2 gói thẳng hàng
  planCardFree: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 16,
    padding: 20,
  },
  planNameFree: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1E293B',
  },
  planDescFree: {
    fontSize: 13,
    color: '#64748B',
    marginTop: 2,
    marginBottom: 12,
  },
  planPriceFree: {
    fontSize: 28,
    fontWeight: '900',
    color: '#0F172A',
    marginBottom: 16,
  },
  featuresList: {
    gap: 10,
    marginBottom: 20,
  },
  featureItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  featureIcon: {
    fontSize: 14,
    color: '#15803D',
    fontWeight: 'bold',
  },
  featureIconDisabled: {
    color: '#CBD5E1',
  },
  featureText: {
    fontSize: 15,
    color: '#334155',
  },
  featureTextDisabled: {
    color: Colors.secondary,
    textDecorationLine: 'line-through',
  },
  freeBtn: {
    height: 44,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
  },
  freeBtnText: {
    color: '#64748B',
    fontSize: 13,
    fontWeight: '600',
  },
  planCardPremium: {
    backgroundColor: Colors.brandNavy,
    boxShadow: '0 20px 40px -20px rgba(11, 42, 85, 0.55)',
    borderRadius: 16,
    padding: 20,
    position: 'relative',
    overflow: 'hidden',
  },
  premiumGlow: {
    position: 'absolute', right: -70, top: -110, width: 260, height: 260, borderRadius: 130,
    backgroundColor: 'rgba(8, 168, 128, 0.35)', filter: 'blur(40px)',
  },
  premiumShine: {
    position: 'absolute', top: -60, bottom: -60, width: 90,
    backgroundColor: 'rgba(164, 251, 229, 0.10)',
  },
  popularBadge: {
    position: 'absolute',
    top: 14,
    right: 14,
    backgroundColor: Colors.brandMint,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  popularBadgeText: {
    color: Colors.brandNavy,
    fontSize: 11,
    fontWeight: 'bold',
  },
  planNamePremium: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  planDescPremium: {
    fontSize: 13,
    color: '#B9C9E0',
    paddingRight: 100,
    marginTop: 2,
    marginBottom: 12,
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    marginBottom: 16,
  },
  planPricePremium: {
    fontSize: 36,
    fontWeight: '900',
    color: '#FFFFFF',
    fontVariant: ['tabular-nums'],
  },
  planPeriodPremium: {
    fontSize: 15,
    color: Colors.brandMint,
    marginLeft: 4,
  },
  featureIconPremium: {
    fontSize: 14,
    color: '#86EFAC',
    fontWeight: 'bold',
  },
  featureTextPremium: {
    fontSize: 15,
    color: '#F1F5F9',
  },
  premiumBtn: {
    height: 48,
    backgroundColor: Colors.brandMint,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  premiumBtnHover: { backgroundColor: '#C6FFF0' },
  premiumBtnText: {
    color: Colors.brandNavy,
    fontSize: 15,
    fontWeight: 'bold',
  },
  cancelRenewBtn: {
    height: 36,
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    borderWidth: 1,
    borderColor: '#EF4444',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelRenewBtnText: {
    color: '#EF4444',
    fontSize: 12,
    fontWeight: 'bold',
  },
  expireNoticeText: {
    color: '#BBF7D0',
    fontSize: 11,
    textAlign: 'center',
    marginTop: 8,
    fontStyle: 'italic',
  },
  popupOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  popupCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 32,
    alignItems: 'center',
    width: '100%',
    maxWidth: 420,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 15,
    elevation: 5,
  },
  popupIconCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  popupIconText: {
    fontSize: 28,
    fontWeight: 'bold',
  },
  popupTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#0F172A',
    marginBottom: 10,
    textAlign: 'center',
  },
  popupMessage: {
    fontSize: 14,
    color: '#64748B',
    lineHeight: 22,
    textAlign: 'center',
    marginBottom: 28,
  },
  popupButtonsRow: {
    flexDirection: 'row',
    gap: 12,
    width: '100%',
  },
  popupButton: {
    flex: 1,
    height: 48,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  popupCancelButton: {
    backgroundColor: '#F1F5F9',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  popupCancelButtonText: {
    color: '#475569',
    fontSize: 14,
    fontWeight: '600',
  },
  popupButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  popupSingleButton: {
    width: '100%',
    height: 48,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  trustContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 28,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#E2E8F0',
    paddingVertical: 14,
  },
  trustItem: {
    flex: 1,
    alignItems: 'center',
    gap: 4,
  },
  trustIcon: {
    fontSize: 16,
  },
  trustText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#475569',
    textAlign: 'center',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#0F172A',
    marginBottom: 12,
    textAlign: 'center',
  },
  faqList: {
    gap: 10,
    marginBottom: 20,
  },
  faqCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#F1F5F9',
    borderRadius: 12,
    overflow: 'hidden',
  },
  faqQuestionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 14,
  },
  faqQuestion: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1E293B',
    flex: 1,
    paddingRight: 10,
  },
  faqArrow: {
    fontSize: 10,
    color: '#94A3B8',
  },
  faqAnswerContainer: {
    paddingHorizontal: 14,
    paddingBottom: 14,
    borderTopWidth: 1,
    borderTopColor: '#F8FAFC',
    paddingTop: 8,
  },
  faqAnswer: {
    fontSize: 12,
    color: '#64748B',
    lineHeight: 18,
  },
});
