import { StyleSheet } from 'react-native';
import Colors from '../constants/colors';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: Colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  backButton: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingVertical: 4, marginRight: 16, minHeight: 44 },
  backButtonText: { fontSize: 14, color: Colors.slateMuted, fontWeight: '500' },
  headerTitle: { fontSize: 18, fontWeight: '700', color: Colors.brandNavy },

  scrollContainer: { paddingHorizontal: 16, paddingVertical: 20, paddingBottom: 40 },
  scrollContainerDesktop: { paddingHorizontal: 32, paddingVertical: 28, maxWidth: 900, width: '100%', alignSelf: 'center' },
  titleContainer: { marginBottom: 20 },

  contactRow: { flexDirection: 'row', gap: 12, marginBottom: 28 },
  contactColumn: { flexDirection: 'column' },
  contactCell: { flex: 1 },
  contactCellInner: { flex: 1 },
  contactCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 14,
    minHeight: 72,
    flex: 1,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 14,
  },
  contactCardHover: { borderColor: Colors.brandGreen, boxShadow: '0 10px 24px -14px rgba(11, 42, 85, 0.35)' },
  contactIconBg: { width: 40, height: 40, borderRadius: 12, backgroundColor: Colors.brandGreenSoft, alignItems: 'center', justifyContent: 'center' },
  contactText: { flex: 1 },
  contactTitle: { fontSize: 15, fontWeight: '700', color: Colors.brandNavy },
  contactDesc: { fontSize: 13, color: Colors.secondary, marginTop: 2, fontVariant: ['tabular-nums'] },

  sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 },
  sectionTitle: { fontSize: 18, fontWeight: '700', color: Colors.brandNavy },
  sectionTitleSpaced: { marginTop: 8, marginBottom: 12 },
  linkBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, height: 36, paddingHorizontal: 12, borderRadius: 8 },
  linkBtnHover: { backgroundColor: Colors.brandGreenSoft },
  linkBtnText: { fontSize: 14, color: Colors.brandGreen, fontWeight: '600' },

  ticketsCard: {
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 16,
    paddingHorizontal: 16,
    marginBottom: 28,
  },
  emptyBox: { alignItems: 'center', paddingVertical: 12 },
  emptyIllus: { width: 120, height: 120 },
  emptyText: { color: Colors.secondary, fontSize: 14, textAlign: 'center', paddingBottom: 8 },
  ticketRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  lastTicketRow: { borderBottomWidth: 0 },
  ticketLeft: { flex: 1 },
  ticketTopic: { fontSize: 13, fontWeight: '600', color: Colors.brandGreen, marginBottom: 2 },
  ticketSubject: { fontSize: 15, color: Colors.slateDark, lineHeight: 21 },
  ticketMeta: { fontSize: 12, color: Colors.secondary, marginTop: 4, fontVariant: ['tabular-nums'] },
  statusBadge: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 10, paddingVertical: 4, borderRadius: 999 },
  statusText: { fontSize: 12, fontWeight: '700' },

  faqList: { gap: 10, marginBottom: 28 },
  faqCard: { backgroundColor: Colors.surface, borderWidth: 1, borderColor: Colors.border, borderRadius: 14, overflow: 'hidden' },
  faqCardOpen: { borderColor: '#CDEBDF' },
  faqQuestionRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12, padding: 16, minHeight: 52 },
  faqQuestionRowHover: { backgroundColor: '#F8FAFC' },
  faqQuestion: { fontSize: 15, fontWeight: '600', color: Colors.slateDark, flex: 1 },
  faqAnswerContainer: { paddingHorizontal: 16, paddingBottom: 16 },
  faqAnswer: { fontSize: 15, color: Colors.slateMuted, lineHeight: 23 },

  formCard: {
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
  },
  formTitle: { fontSize: 18, fontWeight: '700', color: Colors.brandNavy },
  formDesc: { fontSize: 14, color: Colors.secondary, marginTop: 2, marginBottom: 18 },
  label: { fontSize: 13, fontWeight: '600', color: Colors.slateMuted, marginBottom: 6 },
  dropdownTrigger: {
    height: 46,
    borderWidth: 1,
    borderColor: Colors.borderStrong,
    borderRadius: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 14,
    marginBottom: 14,
    backgroundColor: Colors.surface,
  },
  dropdownTriggerOpen: { borderColor: Colors.brandGreen },
  dropdownTriggerHover: { borderColor: Colors.brandGreen },
  dropdownTriggerText: { fontSize: 15, color: Colors.slateDark },
  dropdownPlaceholder: { color: Colors.secondary },
  dropdownMenu: {
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 10,
    marginTop: -8,
    marginBottom: 14,
    overflow: 'hidden',
    boxShadow: '0 8px 20px -10px rgba(15, 23, 42, 0.25)',
  },
  dropdownOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 44,
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  dropdownOptionHover: { backgroundColor: '#F8FAFC' },
  dropdownOptionActive: { backgroundColor: Colors.brandGreenSoft },
  dropdownOptionText: { fontSize: 15, color: Colors.slateMuted },
  dropdownOptionTextActive: { color: Colors.brandGreen, fontWeight: '600' },
  textarea: {
    borderWidth: 1,
    borderColor: Colors.borderStrong,
    borderRadius: 10,
    padding: 14,
    minHeight: 110,
    fontSize: 15,
    color: Colors.slateDark,
    backgroundColor: Colors.surface,
    textAlignVertical: 'top',
    marginBottom: 12,
  },
  formError: { fontSize: 13, color: Colors.error, marginBottom: 12 },
  sendBtn: {
    height: 48,
    backgroundColor: Colors.brandGreen,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 4,
    boxShadow: '0 6px 14px -6px rgba(6, 122, 94, 0.45)',
  },
  sendBtnHover: { backgroundColor: Colors.brandGreenPressed },
  sendBtnText: { color: '#FFFFFF', fontSize: 15, fontWeight: '700' },
});
