import { StyleSheet, Platform, Dimensions } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  backButton: {
    paddingVertical: 4,
    marginRight: 16,
  },
  backButtonText: {
    fontSize: 14,
    color: '#64748B',
    fontWeight: '500',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#0F172A',
  },
  scrollContainer: {
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  syncBanner: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#ECFDF5',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#A7F3D0',
  },
  syncLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  syncIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#10B981',
  },
  syncStatusText: {
    color: '#065F46',
    fontSize: 11,
    fontWeight: 'bold',
  },
  syncTime: {
    color: '#047857',
    fontSize: 10,
  },
  titleContainer: {
    marginBottom: 16,
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#0F172A',
  },
  metricsGrid: {
    gap: 12,
    marginBottom: 24,
  },
  metricRow: {
    flexDirection: 'row',
    gap: 12,
  },
  metricCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 14,
    padding: 14,
  },
  metricLabel: {
    fontSize: 8,
    fontWeight: 'bold',
    color: '#94A3B8',
    marginBottom: 6,
    letterSpacing: 0.5,
  },
  metricValue: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#0F172A',
    marginBottom: 8,
  },
  barBg: {
    height: 4,
    backgroundColor: '#E2E8F0',
    borderRadius: 2,
  },
  barFill: {
    height: '100%',
    backgroundColor: '#15803D',
    borderRadius: 2,
  },
  metricSub: {
    fontSize: 11,
    color: '#64748B',
    fontWeight: '500',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#0F172A',
  },
  updateBtn: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#15803D',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  updateBtnText: {
    color: '#15803D',
    fontSize: 11,
    fontWeight: '600',
  },
  agentCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
  },
  agentHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  agentTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  agentEmoji: {
    fontSize: 16,
  },
  agentName: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#0F172A',
  },
  activeTag: {
    backgroundColor: '#DCFCE7',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  activeTagText: {
    color: '#166534',
    fontSize: 9,
    fontWeight: 'bold',
  },
  agentDesc: {
    fontSize: 12,
    color: '#64748B',
    lineHeight: 18,
    marginBottom: 16,
  },
  sliderContainer: {
    marginBottom: 12,
  },
  sliderLabelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  sliderText: {
    fontSize: 12,
    color: '#475569',
  },
  sliderValue: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#0F172A',
  },
  sliderTrack: {
    height: 4,
    backgroundColor: '#F1F5F9',
    borderRadius: 2,
    position: 'relative',
    justifyContent: 'center',
  },
  sliderFill: {
    height: '100%',
    backgroundColor: '#15803D',
    borderRadius: 2,
  },
  sliderThumb: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#15803D',
    position: 'absolute',
    transform: [{ translateX: -5 }],
  },
  viewMoreLink: {
    alignItems: 'center',
    paddingVertical: 10,
    marginBottom: 16,
  },
  viewMoreText: {
    fontSize: 13,
    color: '#15803D',
    fontWeight: '600',
  },
  hardCasesCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 16,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
  },
  hardCasesLeft: {
    flex: 1.5,
    paddingRight: 10,
  },
  hardCasesTitle: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#0F172A',
    marginBottom: 4,
  },
  hardCasesDesc: {
    fontSize: 11,
    color: '#64748B',
    lineHeight: 16,
  },
  hardCasesRight: {
    flex: 1,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  hardCasesCount: {
    fontSize: 12,
    color: '#64748B',
    marginBottom: 6,
  },
  deployBtnMini: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#15803D',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  deployBtnTextMini: {
    color: '#15803D',
    fontSize: 11,
    fontWeight: 'bold',
  },
  ragContainer: {
    backgroundColor: '#0F172A',
    borderRadius: 16,
    padding: 16,
    marginBottom: 24,
  },
  ragHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#1E293B',
    paddingBottom: 12,
  },
  ragTitle: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: 'bold',
  },
  ragSubtitle: {
    color: '#94A3B8',
    fontSize: 11,
    marginTop: 2,
  },
  addDocBtn: {
    backgroundColor: '#15803D',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  addDocText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: 'bold',
  },
  ragStatusCard: {
    backgroundColor: '#1E293B',
    borderRadius: 12,
    padding: 14,
    marginBottom: 16,
  },
  ragVectorCount: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  ragVectorDesc: {
    fontSize: 11,
    color: '#94A3B8',
    lineHeight: 16,
  },
  documentHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  docHeaderTitle: {
    color: '#94A3B8',
    fontSize: 9,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  docSyncStatus: {
    color: '#4ADE80',
    fontSize: 9,
    fontWeight: 'bold',
  },
  docList: {
    gap: 8,
    marginBottom: 20,
  },
  docRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1E293B',
    padding: 10,
    borderRadius: 10,
    gap: 10,
  },
  docIcon: {
    width: 28,
    height: 28,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
  },
  docIconText: {
    fontSize: 14,
  },
  docInfo: {
    flex: 1,
  },
  docName: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '500',
  },
  docMeta: {
    color: '#94A3B8',
    fontSize: 10,
    marginTop: 2,
  },
  moreIcon: {
    color: '#94A3B8',
    fontSize: 16,
    paddingHorizontal: 6,
  },
  sliderContainerDark: {
    marginTop: 8,
  },
  sliderLabelRowDark: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  sliderTextDark: {
    fontSize: 12,
    color: '#94A3B8',
  },
  sliderValueDark: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  sliderTrackDark: {
    height: 4,
    backgroundColor: '#334155',
    borderRadius: 2,
    position: 'relative',
    justifyContent: 'center',
  },
  sliderFillDark: {
    height: '100%',
    backgroundColor: '#22C55E',
    borderRadius: 2,
  },
  sliderThumbDark: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#22C55E',
    position: 'absolute',
    transform: [{ translateX: -5 }],
  },
  promptCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
  },
  promptHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  promptTitle: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#0F172A',
  },
  promptIcon: {
    fontSize: 12,
  },
  promptInput: {
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    padding: 12,
    fontSize: 12,
    color: '#64748B',
    lineHeight: 18,
    textAlignVertical: 'top',
  },
});
