import { StyleSheet, Platform, Dimensions } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  // NAVBAR STYLES
  navbar: {
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    zIndex: 10,
    width: '100%',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 3,
      },
      android: {
        elevation: 2,
      },
      web: {
        position: 'sticky',
        top: 0,
      }
    }),
  },
  navbarContainer: {
    height: 70,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    maxWidth: 1200,
    alignSelf: 'center',
    width: '100%',
  },
  brandContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  logoCircle: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#15803D',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  logoInner: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  brandName: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#0F172A',
    lineHeight: 18,
  },
  brandSub: {
    fontSize: 8,
    fontWeight: 'bold',
    color: '#15803D',
  },
  navLinks: {
    flexDirection: 'row',
    gap: 24,
  },
  navLinkText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#475569',
    paddingVertical: 8,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  bookingBtn: {
    backgroundColor: '#0284C7',
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 20,
  },
  bookingBtnText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: 'bold',
  },
  loginBtn: {
    backgroundColor: '#15803D',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
  },
  loginBtnText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: 'bold',
  },
  mobileMenuBtn: {
    padding: 8,
    marginLeft: 4,
  },
  menuIconText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#334155',
  },
  mobileDropdown: {
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  mobileNavLink: {
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderBottomWidth: 1,
    borderBottomColor: '#F8FAFC',
  },
  mobileNavLinkText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#334155',
  },

  // HERO STYLES
  scrollContainer: {
    alignItems: 'stretch',
  },
  heroDesktop: {
    flexDirection: 'row',
    minHeight: 480,
    backgroundColor: '#F8FAFC',
    maxWidth: 1200,
    alignSelf: 'center',
    width: '100%',
    paddingHorizontal: 24,
    alignItems: 'center',
    gap: 40,
    paddingVertical: 40,
  },
  heroMobile: {
    flexDirection: 'column',
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 24,
    paddingVertical: 32,
    gap: 24,
  },
  heroLeft: {
    flex: 1,
    justifyContent: 'center',
  },
  heroFullWidth: {
    width: '100%',
  },
  heroRight: {
    flex: 1.1,
    height: 400,
    borderRadius: 24,
    overflow: 'hidden',
    position: 'relative',
    elevation: 8,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
  },
  heroImageContainerMobile: {
    width: '100%',
    height: 240,
    borderRadius: 16,
    overflow: 'hidden',
    position: 'relative',
  },
  heroBgImage: {
    width: '100%',
    height: '100%',
  },
  heroImgOverlay: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(21, 128, 61, 0.15)', // transparent medical green tint
  },
  heroPreTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#0284C7',
    letterSpacing: 1.5,
    marginBottom: 12,
  },
  heroTitle: {
    fontSize: 42,
    fontWeight: '900',
    color: '#0F172A',
    lineHeight: 52,
    marginBottom: 16,
  },
  heroDesc: {
    fontSize: 15,
    color: '#475569',
    lineHeight: 24,
    marginBottom: 28,
  },
  heroActions: {
    flexDirection: 'row',
    gap: 16,
  },
  ctaPrimary: {
    backgroundColor: '#15803D',
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 24,
    elevation: 2,
  },
  ctaPrimaryText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 14,
  },
  ctaSecondary: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#15803D',
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 24,
  },
  ctaSecondaryText: {
    color: '#15803D',
    fontWeight: 'bold',
    fontSize: 14,
  },
  floatingStats: {
    position: 'absolute',
    bottom: 24,
    left: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  floatingStatsVal: {
    fontSize: 22,
    fontWeight: '900',
    color: '#15803D',
  },
  floatingStatsLabel: {
    fontSize: 11,
    color: '#475569',
    fontWeight: '500',
    marginTop: 2,
  },

  // FLOATING QUICK ACCESS BAR
  quickAccessWrapper: {
    maxWidth: 1200,
    alignSelf: 'center',
    width: '100%',
    paddingHorizontal: 24,
    marginTop: -30,
    zIndex: 5,
  },
  quickAccessBar: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    elevation: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
  },
  rowBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  colBar: {
    flexDirection: 'column',
    gap: 16,
  },
  quickAccessItem: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 8,
  },
  quickAccessIcon: {
    fontSize: 24,
    marginRight: 12,
  },
  quickAccessLabel: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#1E293B',
  },
  vDivider: {
    width: 1,
    height: 30,
    backgroundColor: '#E2E8F0',
  },
  hDivider: {
    height: 1,
    width: '100%',
    backgroundColor: '#F1F5F9',
  },

  // INTRO & SECTIONS
  sectionContainer: {
    paddingHorizontal: 24,
    paddingVertical: 56,
    maxWidth: 1200,
    alignSelf: 'center',
    width: '100%',
  },
  rowLayout: {
    flexDirection: 'row',
    gap: 32,
  },
  columnLayout: {
    flexDirection: 'column',
    gap: 24,
  },
  introRow: {
    alignItems: 'stretch',
  },
  introLeftText: {
    flex: 1.6,
  },
  sectionHeading: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#0F172A',
    marginBottom: 20,
  },
  introText: {
    fontSize: 14,
    color: '#475569',
    lineHeight: 22,
    marginBottom: 14,
  },
  contactCard: {
    flex: 1,
    backgroundColor: '#F0FDF4',
    borderWidth: 1,
    borderColor: '#DCFCE7',
    borderRadius: 16,
    padding: 24,
    justifyContent: 'center',
  },
  contactCardTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#15803D',
    marginBottom: 20,
    borderBottomWidth: 2,
    borderBottomColor: '#DCFCE7',
    paddingBottom: 8,
  },
  contactCardItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  contactCardIcon: {
    fontSize: 20,
    marginRight: 12,
    marginTop: 2,
  },
  contactCardLabel: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#64748B',
    marginBottom: 2,
  },
  contactCardValue: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1E293B',
    lineHeight: 20,
  },

  // SERVICES GRID SECTION
  sectionCenterTitle: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#0F172A',
    textAlign: 'center',
    marginBottom: 8,
  },
  sectionCenterSub: {
    fontSize: 14,
    color: '#64748B',
    textAlign: 'center',
    marginBottom: 40,
    paddingHorizontal: 20,
  },
  servicesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
    justifyContent: 'center',
  },
  serviceCard: {
    width: '45%',
    maxWidth: 160,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    marginBottom: 8,
  },
  serviceIconCircle: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#F0FDF4',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  serviceCardIcon: {
    fontSize: 24,
  },
  serviceCardTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#1E293B',
    textAlign: 'center',
    lineHeight: 16,
  },

  // PACKAGES SECTION
  packagesContainer: {
    alignItems: 'stretch',
  },
  packageCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 16,
    overflow: 'hidden',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
  },
  packageImageContainer: {
    height: 160,
    width: '100%',
    position: 'relative',
  },
  packageImage: {
    width: '100%',
    height: '100%',
  },
  packageTagContainer: {
    position: 'absolute',
    bottom: 12,
    left: 12,
    backgroundColor: '#0284C7',
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 4,
  },
  packageTagText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: 'bold',
  },
  packageContent: {
    padding: 16,
    flex: 1,
  },
  packageTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#1E293B',
    marginBottom: 8,
    lineHeight: 20,
    minHeight: 40,
  },
  packageDesc: {
    fontSize: 12,
    color: '#64748B',
    lineHeight: 18,
    marginBottom: 16,
    flex: 1,
  },
  pkgBtn: {
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    paddingTop: 12,
    alignItems: 'flex-start',
  },
  pkgBtnText: {
    color: '#0284C7',
    fontSize: 12,
    fontWeight: 'bold',
  },

  // DOCTORS SECTION
  doctorsContainer: {
    alignItems: 'stretch',
  },
  doctorCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 16,
    overflow: 'hidden',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
  },
  doctorImagePlaceholder: {
    height: 200,
    width: '100%',
    backgroundColor: '#EFF6FF',
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  doctorPlaceHolderText: {
    fontSize: 48,
  },
  doctorImageLabel: {
    fontSize: 12,
    color: '#94A3B8',
    fontWeight: 'bold',
    marginTop: 8,
  },
  doctorContent: {
    padding: 16,
  },
  doctorName: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#1E293B',
    marginBottom: 4,
  },
  doctorRole: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#15803D',
    marginBottom: 8,
  },
  doctorDesc: {
    fontSize: 12,
    color: '#64748B',
    lineHeight: 18,
  },

  // FOOTER SECTION
  footer: {
    backgroundColor: '#0F172A',
    paddingTop: 56,
  },
  footerContainer: {
    maxWidth: 1200,
    alignSelf: 'center',
    width: '100%',
    paddingHorizontal: 24,
    paddingBottom: 40,
    borderBottomWidth: 1,
    borderBottomColor: '#1E293B',
  },
  footerCol: {
    flex: 1,
    marginBottom: 28,
  },
  footerIntroText: {
    fontSize: 12,
    color: '#94A3B8',
    lineHeight: 20,
    maxWidth: 260,
  },
  footerColTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 16,
  },
  footerLink: {
    fontSize: 12,
    color: '#94A3B8',
    marginBottom: 10,
  },
  footerContactText: {
    fontSize: 12,
    color: '#94A3B8',
    marginBottom: 12,
    lineHeight: 18,
  },
  footerBottom: {
    paddingVertical: 24,
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  footerBottomText: {
    fontSize: 11,
    color: '#64748B',
    textAlign: 'center',
  },
});
